services:
  db:
    image: postgres:16
    container_name: todo_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - todoapp_pg:/var/lib/postgresql/data

volumes:
  todoapp_pg:
